apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapp-nasp.fullname" . }}
  labels:
    {{- include "rapp-nasp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rapp-nasp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rapp-nasp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["python3"]
          #args: ["rApp_NASP.py", "-c", "config/config.yaml"]
          ports:
            - name: http
              containerPort: {{ .Values.app.api_server.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              subPath: config.yaml
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 17 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 17 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "rapp-nasp.fullname" . }}-config
        {{- with .Values.volumes }}
        - {{ toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}