apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapp-nasp.fullname" . }}
  labels:
    {{- include "rapp-nasp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rapp-nasp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.api_server.port }}
      protocol: TCP