# Logging configuration
logging:
  level: DEBUG # Logging level


# Non-RT RIC configuration
nonrtric:
  #base_url_rApp_catalogue: 'http://rappcatalogueservice.nonrtric.svc.cluster.local:9085/services'
  base_url_rApp_catalogue: 'http://10.101.138.54:9085/services'
  #base_url_pms: 'http://nonrtricgateway.nonrtric.svc.cluster.local:9090/a1-policy/v2'
  base_url_pms: 'http://10.111.85.136:9090/a1-policy/v2'
  service_name: 'rAppNASP'
  service_version: 'v1'
  service_display_name: 'rApp NASP'
  service_description: 'Application for optimizing network slicing'
  ric_id: 'ric4'
  policytype_id: '1'

api_server:
  host: '0.0.0.0'  # Host address for the API server
  port: 5000       # Port number for the API server